# Generated by Django 2.0.9 on 2018-10-31 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Записи',
                'db_table': 'journal_record',
                'verbose_name': 'Запись',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ФИО мастера')),
                ('vacant_days', models.CharField(default='6,7', max_length=50)),
                ('vacant_hours', models.CharField(default='18-9, 13-14', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Мастера',
                'db_table': 'master',
                'verbose_name': 'Мастер',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование услуги')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('time_elapsed', models.IntegerField(verbose_name='Кол-во получасов')),
            ],
            options={
                'verbose_name_plural': 'Услуги',
                'db_table': 'service',
                'verbose_name': 'Услуга',
            },
        ),
        migrations.AddField(
            model_name='journalrecord',
            name='master',
            field=models.ForeignKey(db_column='master_id', on_delete=django.db.models.deletion.CASCADE, to='core.Master', verbose_name='Назначенный мастер'),
        ),
        migrations.AddField(
            model_name='journalrecord',
            name='service',
            field=models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='core.Service', verbose_name='Услуга'),
        ),
    ]
