# Generated by Django 2.0.9 on 2018-10-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalrecord',
            name='client',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='journalrecord',
            name='time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
