# Generated by Django 2.0.9 on 2018-10-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181031_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalrecord',
            name='time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
