# Generated by Django 2.0.9 on 2018-11-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_master_photo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='resume',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
