"""
Django settings for astra project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^c)0+jzfsfm6fs!v=5+2vu$=2x@d=_2-%8*4d1&gr(m9g-o(l='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.1.30',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app_customer',
    'app_admin',
    'bootstrap3',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'astra.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'astra.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Yekaterinburg'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(os.path.abspath(BASE_DIR), 'static')

print(STATIC_ROOT)
STATICFILES_DIRS = [
    # os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(os.path.abspath(BASE_DIR), 'media')

SITE_SETTINGS = {
    # required settings
    'site_name': 'Astra',
    'c_site_name': 'Салон красоты Астра',
    # 'shop_email': 'uskoritel59@yandex.ru',
    # 'admin_email': 'alarionov93@yandex.ru',
    # 'company_phones': [
        # '8 (342) 203-23-43',
        # '8 (342) 263-17-17'
    # ],
    # 'company_addresses': [
        # 'г. Пермь, ул. Пушкарская, 132',
        # 'г. Пермь, ул. Соликамская, 271 А'
    # ],
    # 'news_lifetime': 60, # integer value in days
    # 'min_order_sum': 0,
    # web panel report error
    # 'web_panel_report_error_url': 'http://a-larionov.ru:5001/reports/new',
    # 'event_group_id': 6, # 6 for web panel production srv
    # non required settings
    # used for order creation form to show or not show
    # address field, and other fields needed for delivery
    # 'delivery_type_id_to_show_address': const.DELIVERY_TYPE_ID_HOME,
    # 'delivery_type_self_id': const.DELIVERY_TYPE_ID_SHOP,
    # 'delivery_price': 150,
    # 'discount': False,
    # 'delivery_out_city_price': 250, 
    # 'end_of_free_ship': '11.11.2016',
    # 'min_order_sum_settings': {'do_not_check': False, 'product_id_to_cancel_min_order_sum': None},
    #'min_order_sum_settings': {'do_not_check': True, 'product_id_to_cancel_min_order_sum': 164}, # set it to enable min order sum cancelling
    # 'orders_show_from_delta_days': 60,
    # 'payments_enabled': True # to temporary switch off payments
}
# # default value for order items statistics
# # DEFAULT_STAT_PERIOD = 15

INTERNAL_IPS = (
    '0.0.0.0',
    '127.0.0.1',
)

# REST_FRAMEWORK = {
#     'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.AllowAny',),
#     # 'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAdminUser',),
#     # 'DEFAULT_AUTHENTICATION_CLASSES': (
#     #     'rest_framework.authentication.BasicAuthentication',
#     #     'rest_framework.authentication.SessionAuthentication',
#     # ),
#     'PAGE_SIZE': 10
# }
# USER_DETAILS_SERIALIZER = UserSerializer

# Email settings SMTP

# EMAIL_HOST = 'smtp.yandex.ru'

# EMAIL_PROVIDER = 'yandex.ru'

# EMAIL_PORT = 465

# EMAIL_HOST_USER = 'alarionov93'

# EMAIL_HOST_PASSWORD = 'TRANSALPrd10e2001125'

# EMAIL_USE_SSL = True

# MAIL_FAIL_SILENT = False

# ADMIN_EMAIL = '%s@%s' % (EMAIL_HOST_USER, EMAIL_PROVIDER)

# DEFAULT_FROM_EMAIL = ADMIN_EMAIL
